### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by szTom** [mark-hahn/markdown-scroll-sync#1298]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.12
**OS**: linux 5.5.13-arch2-1
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/toma/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:519:20)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.item (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:333:20)
    at PaneContainer.didActivatePane (/usr/lib/atom/src/pane-container.js:308:12)
    at Pane.activate (/usr/lib/atom/src/pane.js:1112:40)
    at Pane.focus (/usr/lib/atom/src/pane.js:416:17)
    at HTMLElement.handleFocus (/usr/lib/atom/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
markdown-image-paste 2.5.2 
markdown-preview-plus 3.11.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.2 
pretty-json 2.1.2 
```

**Comment by szTom** [comment]
$ reboot
-------
...

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.12
**OS**: linux 5.6.2-arch1-2
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2


### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Workspace.observeActivePaneItem (/usr/lib/atom/src/workspace.js:841:5)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:25:30)
    at Package.activateNow (/usr/lib/atom/src/package.js:241:27)
    at measure (/usr/lib/atom/src/package.js:210:27)
    at Package.measure (/usr/lib/atom/src/package.js:81:19)
    at activationPromise.Promise (/usr/lib/atom/src/package.js:204:14)
    at new Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:202:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:790:36)
    at config.transactAsync (/usr/lib/atom/src/package-manager.js:765:30)
    at Config.transactAsync (/usr/lib/atom/src/config.js:925:22)
    at PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:763:17)
    at PackageManager.activate (/usr/lib/atom/src/package-manager.js:740:44)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:1017:21)
```

### Commands

```
```

### Non-Core Packages

```
markdown-image-paste 2.5.2 
markdown-preview-plus 3.11.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.2 
pretty-json 2.1.2 
```
