### ISSUE TITLE
Failed to activate the markdown-scroll-sync package

### ISSUE THREAD

**Issue by 0xC4FED6C7CCCE** [mark-hahn/markdown-scroll-sync#1396]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.6
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Cannot find module '/Users/mac/.atom/packages/markdown-preview-plus/lib/markdown-preview-view'
Require stack:
- /Users/mac/.atom/packages/markdown-scroll-sync/lib/main.coffee
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module '/Users/mac/.atom/packages/markdown-preview-plus/lib/markdown-preview-view'
Require stack:
- /Users/mac/.atom/packages/markdown-scroll-sync/lib/main.coffee
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146720)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:23:28)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3531055)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530467
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3528045)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530327
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530270)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383646)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:916751
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911357)
    at s (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121312)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121400
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1120068)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -0:50.3.0 settings-view:open (atom-pane.pane.active)
     -0:47.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
markdown-preview-plus 4.9.0 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.3 
```

**Comment by under-score** [comment]
same here
