### ISSUE TITLE
Failed to activate the markdown-scroll-sync package

### ISSUE THREAD

**Issue by marneylc** [mark-hahn/markdown-scroll-sync#1473]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Pop!_OS 22.04
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Cannot find module '/home/salamander/.atom/packages/markdown-preview-plus/lib/markdown-preview-view'
Require stack:
- /home/salamander/.atom/packages/markdown-scroll-sync/lib/main.coffee
- /usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module '/home/salamander/.atom/packages/markdown-preview-plus/lib/markdown-preview-view'
Require stack:
- /home/salamander/.atom/packages/markdown-scroll-sync/lib/main.coffee
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149207)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:23:28)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3388634)
    at /usr/share/atom/resources/app/static/<embedded>:11:3388046
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3385624)
    at /usr/share/atom/resources/app/static/<embedded>:11:3387906
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3387849)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:385612)
    at /usr/share/atom/resources/app/static/<embedded>:11:385228
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:334752)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:385178)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:384728)
    at /usr/share/atom/resources/app/static/<embedded>:1:778470
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app/static/<embedded>:1:779007)
```

### Commands

```
     -2:11.6.0 platformio-ide-terminal:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-horizon-syntax 0.2.0 
atom-horizon-ui 0.2.0 
atom-material-syntax 1.0.8 
autocomplete-python 1.17.1 
ayu 0.1.0 
ayu-dark-syntax 0.1.0 
ayu-mirage-syntax 0.1.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
ex-mode 0.18.0 
go-plus 6.1.0 
Hydrogen 2.16.3 
hydrogen-launcher 1.2.2 
isotope-ui 2.8.5 
language-docker 1.1.8 
language-markdown 0.37.0 
language-r 0.4.2 
language-singularity 2.1.0 
markdown-pdf 2.3.3 
markdown-preview-plus 4.11.1 
markdown-scroll-sync 2.1.2 
markdown-toc-auto 0.14.1 
markdown-writer 2.11.12 
minimap 4.40.1 
monokai 0.28.0 
nucleus-dark-ui 0.12.3 
package-sync 1.1.0 
pdf-view 0.73.0 
platformio-ide-terminal 2.10.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
seti-ui-red 0.13.0 
tool-bar 1.4.4 
tool-bar-markdown-writer 0.5.1 
vim-mode-plus 1.36.7 
```

**Comment by marneylc** [comment]
Looks like it looking for markdown-preview-view in lib when its in src

.atom/packages/markdown-preview-plus/src/markdown-preview-view/
