### ISSUE TITLE
Failed to load the markdown-scroll-sync package

### ISSUE THREAD

**Issue by rui205** [mark-hahn/markdown-scroll-sync#174]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Failed to load the markdown-scroll-sync package

```
At Cannot find module 'sub-atom'

Error: Cannot find module 'sub-atom'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-scroll-sync-master/lib/main.coffee:8:12)
    at /packages/markdown-scroll-sync-master/lib/main.coffee:1:1)
    at /packages/markdown-scroll-sync-master/lib/main.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:887:35)
    at /opt/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/opt/atom/resources/app/src/package-manager.js:565:22)
    at /opt/atom/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/opt/atom/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/opt/atom/resources/app/src/package-manager.js:473:25)
    at /opt/atom/resources/app/src/atom-environment.js:810:34
```

### Commands

```
```

### Non-Core Packages

```
markdown-scroll-sync 2.1.2 
```

**Comment by limuyuan** [comment]
Same issue. Why closed?
