### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by zjunothing** [mark-hahn/markdown-scroll-sync#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.1
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.4.0

### Stack Trace

Uncaught Error: Cannot find module 'underscore'

```
At module.js:330

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/chenliu/.atom/packages/markdown-scroll-sync/node_modules/roaster/lib/roaster.js:8:7)
    at Object.<anonymous> (/Users/chenliu/.atom/packages/markdown-scroll-sync/node_modules/roaster/lib/roaster.js:73:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.4.0
vim-mode, v0.58.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I've released a new version 2.0.1 that is a total rewrite.  I think it fixes all issues and works much better than before.  Please try it.
