### ISSUE TITLE
Failed to activate the markdown-scroll-sync package

### ISSUE THREAD

**Issue by zkcpku** [mark-hahn/markdown-scroll-sync#298]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Workspace.observeActivePaneItem (~/AppData/Local/atom/app-1.23.3/resources/app/src/workspace.js:810:13)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:25:30)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.3/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.3/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
language-markdown 0.25.1 
markdown-image-paste 2.5.2 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.0 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.0.2 
minimap 4.29.7 
simplified-chinese-menu 5.3.5 
```

**Comment by kappapiana** [comment]
Me too

**Comment by addyi** [comment]
Me too after update from markdown-preview-plus to Version 2.5.0

**Comment by gsmetal** [comment]
Same.
It randomly appears and can be fixed by atom restart.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2


### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
  at /packages/markdown-scroll-sync/lib/main.coffee:38:14
  at Workspace.observeActivePaneItem (<embedded>:28248:13)
  at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:25:30)
  at Package.module.exports.Package.activateNow (<embedded>:72535:25)
  at <embedded>:72507:38
  at Package.module.exports.Package.measure (<embedded>:72379:21)
  at <embedded>:72500:32
  at Package.module.exports.Package.activate (<embedded>:72497:40)
  at PackageManager.activatePackage (<embedded>:25356:42)
  at config.transactAsync (<embedded>:25331:36)
  at Config.module.exports.Config.transactAsync (<embedded>:22003:24)
  at PackageManager.activatePackages (<embedded>:25329:23)
  at PackageManager.activate (<embedded>:25308:50)
  at <embedded>:1103:36

```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
atom-ctags 5.1.2 
atom-eco 0.2.0 
atom-material-ui 2.1.1 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-ctags 0.4.1 
blame 1.0.1 
busy-signal 1.4.3 
change-case 0.6.5 
file-icons 2.1.16 
file-watcher 1.2.6 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-ejs 0.4.0 
language-haml 0.25.2 
language-mediawiki 2.2.0 
language-smarty 1.8.0 
language-textile 0.2.0 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-erb 1.1.0 
linter-eslint 8.4.1 
linter-jshint 3.1.6 
linter-markdown 5.2.0 
linter-php 1.5.1 
linter-rubocop 2.2.2 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
markdown-preview-plus 2.5.1 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
pigments 0.40.2 
project-manager 3.3.5 
rails-latest-migration 1.1.6 
rails-partials 0.9.2 
rails-snippets 2.17.0 
ruby-block 0.3.6 
ruby-syntax-replacer 0.5.1 
sequential-number 0.5.0 
string-looper 0.1.2 
sync-settings 0.8.3 
tidy-markdown 3.0.1 
todo-show 2.1.0 
zentabs 0.8.9 
```

**Comment by kappapiana** [comment]
Not even an acknowledgement n fifteen days? Is this an active project at all?

**Comment by yingziwu** [comment]
Me too.

**Atom**: 1.24.0 x64
**Electron**: 1.8.2
**OS**: "Arch Linux"
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2


### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Workspace.observeActivePaneItem (/build/atom/src/atom-1.24.0/out/app/src/workspace.js:693:5)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:25:30)
    at Package.activateNow (/usr/lib/atom/src/package.js:225:27)
    at measure (/usr/lib/atom/src/package.js:201:27)
    at Package.measure (/usr/lib/atom/src/package.js:83:19)
    at activationPromise.Promise (/usr/lib/atom/src/package.js:195:14)
    at Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:193:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:684:36)
    at config.transactAsync (/usr/lib/atom/src/package-manager.js:659:30)
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:365:18)
    at PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:657:17)
    at PackageManager.activate (/usr/lib/atom/src/package-manager.js:636:44)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:827:21)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-csv-markdown 1.0.2 
convert-to-utf8 0.2.4 
git-time-machine 1.5.9 
Hydrogen 2.2.3 
markdown-preview-plus 2.5.5 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
pretty-json 2.0.0 
split-diff 1.5.2 
```

**Comment by taosean** [comment]
Anyone who have solved this problem? I have the same problem here. Can't find a way to solve it.

**Comment by OpenWaygate** [comment]
In fact, this issue comes from the conflict between this package with markdown-preview-plus, you can disable the markdown-preview-plus, then it will work well.

However, what really interesting is, the markdown-preview-plus now can sync scroll, in its setting page.
<img width="568" alt="capture" src="https://user-images.githubusercontent.com/27287694/41596371-b5bf49aa-73fc-11e8-8910-767076316828.PNG">

**Comment by luodexin** [comment]
> In fact, this issue comes from the conflict between this package with markdown-preview-plus, you can disable the markdown-preview-plus, then it will work well.
> 
> However, what really interesting is, the markdown-preview-plus now can sync scroll, in its setting page.
> <img alt="capture" width="568" src="https://user-images.githubusercontent.com/27287694/41596371-b5bf49aa-73fc-11e8-8910-767076316828.PNG">



> In fact, this issue comes from the conflict between this package with markdown-preview-plus, you can disable the markdown-preview-plus, then it will work well.
> 
> However, what really interesting is, the markdown-preview-plus now can sync scroll, in its setting page.
> <img alt="capture" width="568" src="https://user-images.githubusercontent.com/27287694/41596371-b5bf49aa-73fc-11e8-8910-767076316828.PNG">

Thank you

**Comment by luodexin** [comment]
> In fact, this issue comes from the conflict between this package with markdown-preview-plus, you can disable the markdown-preview-plus, then it will work well.
> 
> However, what really interesting is, the markdown-preview-plus now can sync scroll, in its setting page.
> <img alt="capture" width="568" src="https://user-images.githubusercontent.com/27287694/41596371-b5bf49aa-73fc-11e8-8910-767076316828.PNG">

Thank you. it is a good solution
