### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by gunwald** [mark-hahn/markdown-scroll-sync#310]
After I updated to [newest version of markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus/releases/tag/v2.5.1) scroll sync does not work anymore and throws the following error on scrolling in the the markdown pane.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/simon/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/opt/atom/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/opt/atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/opt/atom/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/opt/atom/resources/app/src/pane-container.js:262:18)
    at Pane.activate (/opt/atom/resources/app/src/pane.js:1002:46)
    at Pane.focus (/opt/atom/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
```

### Non-Core Packages

```
adwaita-pro-ui 2.1.5 
autocomplete-bibtex 1.1.0 
color-picker 2.2.5 
language-pfm 0.82.0 
line-length-break 0.4.0 
markdown-footnote 1.1.0 
markdown-preview-plus 2.5.1 
markdown-preview-plus-opener 0.2.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
pandoc-convert 1.1.1 
pandoc-minimal-syntax 0.2.0 
pen-paper-coffee-syntax 0.14.9 
regex-tester 0.2.0 
tool-bar 1.1.4 
tool-bar-markdown-writer 0.3.1 
wordcount 2.10.4 
Zen 0.18.0 
zotero-citations 0.19.1 
zotero-picker 1.5.0 
```

**Comment by misterbridge** [comment]
Yup same, I juste have to open a .md file for this error to show up.
