### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by HubyLiang** [mark-hahn/markdown-scroll-sync#314]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/bonjour/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:436:48)
    at Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -9:04.4.0 editor:newline (input.hidden-input)
 11x -8:58.2.0 core:backspace (input.hidden-input)
 12x -4:46.8.0 editor:newline (input.hidden-input)
     -2:38.1.0 command-palette:toggle (input.hidden-input)
     -2:29.5.0 core:confirm (input.hidden-input)
     -2:29.5.0 settings-view:open (input.hidden-input)
  2x -2:25.3.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
markdown-preview-plus 2.5.1 
markdown-scroll-sync 2.1.2 
vim-mode-plus 1.28.0 
```

**Comment by Beta8383** [comment]
The same.Why all have the same problem?
