### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by dengyouquan** [mark-hahn/markdown-scroll-sync#315]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\烟魂\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (D:/greensoftware/atom-windows/Atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:/greensoftware/atom-windows/Atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (D:/greensoftware/atom-windows/Atom/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (D:/greensoftware/atom-windows/Atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (D:/greensoftware/atom-windows/Atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:/greensoftware/atom-windows/Atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (D:/greensoftware/atom-windows/Atom/resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (D:/greensoftware/atom-windows/Atom/resources/app/src/pane.js:436:48)
    at Pane.activateItem (D:/greensoftware/atom-windows/Atom/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (D:/greensoftware/atom-windows/Atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
```

### Non-Core Packages

```
language-markdown 0.25.1 
markdown-image-paste 2.5.2 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.1 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.0.2 
pdf-view 0.65.0 
simplified-chinese-menu 5.3.5 
```

**Comment by dengyouquan** [comment]
If use markdown-preview-plus,It doesn't work.So use markdown-preview?

**Comment by dengyouquan** [comment]
If use markdown-preview-plus,it doesn't work.So use markdown-preview.
