### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by nobuhiro-kono** [mark-hahn/markdown-scroll-sync#334]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 ia32
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\itako-kono\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.24.0/resources/app/src/workspace.js:477:28)
    at WorkspaceCenter.paneContainer.onDidActivatePane (~/AppData/Local/atom/app-1.24.0/resources/app/src/workspace-center.js:12:59)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane-container.js:264:24)
    at Pane.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:1002:46)
    at Pane.focus (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
 12x -5:11.5.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-plus 2.5.1 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
```

**Comment by huanlin** [comment]
Before this issue is fixed, here is my workaround:

- Uninstall markdown-preview-plus 2.5.x
- Install markdown-preview-plus 2.4.16 with the following command:

    `apm install markdown-preview-plus@2.4.16`

**Comment by WallanceLee** [comment]
@huanlin Thanks! This works for me.

**Comment by Frozoto1** [comment]
@huanlin Thanks! It's nice for me.

**Comment by huanlin** [comment]
You guys might also want to try this: [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced)
 I find it pretty good and use it now.

**Comment by alphyoung** [comment]
Great! done.

**Comment by Mine4ever** [comment]
Thanks，2.4.16 work well.

**Comment by JavaKing2017** [comment]
Thanks ,2.4.16 work well

**Comment by Zhaowenqiang** [comment]
failed Package version: 2.4.16 not found

**Comment by HaveManyHair** [comment]
How to slove Package version:2.4.16 not found

**Comment by Dora-The-Kid** [comment]
https://github.com/atom-community/markdown-preview-plus/tree/v2.4.16
