### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by yanglk2010** [mark-hahn/markdown-scroll-sync#349]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\Administrator\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.24.0/resources/app/src/workspace.js:477:28)
    at WorkspaceCenter.paneContainer.onDidActivatePane (~/AppData/Local/atom/app-1.24.0/resources/app/src/workspace-center.js:12:59)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/

**Comment by gsmetal** [comment]
+1
**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2


### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/gsmetal/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didActivatePaneContainer (/usr/share/atom/resources/app/src/workspace.js:477:28)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/usr/share/atom/resources/app/src/workspace-center.js:12:59)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:264:24)
    at Pane.activate (/usr/share/atom/resources/app/src/pane.js:1002:46)
    at Pane.focus (/usr/share/atom/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
  3x -2:38.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -2:37.7.0 core:move-right (input.hidden-input)
  2x -2:37.7.0 intentions:highlight (input.hidden-input)
     -2:37.2.0 editor:move-to-end-of-word (input.hidden-input)
     -2:35.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
 13x -2:10 core:backspace (input.hidden-input)
     -1:52.1.0 intentions:highlight (input.hidden-input)
  2x -1:52.1.0 editor:move-to-end-of-word (input.hidden-input)
  3x -1:51.5.0 core:backspace (input.hidden-input)
     -0:38.1.0 intentions:highlight (input.hidden-input)
     -0:38 core:save (input.hidden-input)
     -0:26.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:26.4.0 editor:newline (input.hidden-input)
     -0:26.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:26.3.0 editor:newline (input.hidden-input)
  3x -0:25.3.0 core:backspace (input.hidden-input)
```
