### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by kevinSuttle** [mark-hahn/markdown-scroll-sync#36]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v2.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelectorAll' of null

```
At /Users/kevinSuttle/.atom/packages/markdown-scroll-sync/lib/utils.coffee:12

TypeError: Cannot read property 'querySelectorAll' of null
    at MarkdownScrlSync.module.exports.getVisTopHgtBot (/Users/kevinSuttle/.atom/packages/markdown-scroll-sync/lib/utils.coffee:12:38)
    at MarkdownScrlSync.module.exports.setMap (/Users/kevinSuttle/.atom/packages/markdown-scroll-sync/lib/map.coffee:15:8)
    at MarkdownScrlSync.startTracking (/Users/kevinSuttle/.atom/packages/markdown-scroll-sync/lib/main.coffee:49:6)
    at /Users/kevinSuttle/.atom/packages/markdown-scroll-sync/lib/main.coffee:37:14
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:619:15)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:207:21)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -1:15.9.0 core:backspace (input.hidden-input)
     -1:15.1.0 core:save (input.hidden-input)
     -1:09.2.0 command-palette:toggle (input.hidden-input)
     -1:06.2.0 core:confirm (input.hidden-input)
     -1:06.2.0 markdown-preview:toggle (input.hidden-input)
     -0:50.1.0 core:move-left (input.hidden-input)
     -0:48.9.0 editor:move-to-end-of-word (input.hidden-input)
     -0:48.5.0 core:move-left (input.hidden-input)
     -0:48.1.0 core:backspace (input.hidden-input)
  2x -0:47.8.0 editor:move-to-end-of-word (input.hidden-input)
     -0:45.8.0 core:move-left (input.hidden-input)
     -0:38.5.0 core:backspace (input.hidden-input)
     -0:34 core:save (input.hidden-input)
     -0:01.6.0 core:move-left (input.hidden-input)
  2x -0:01.2.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:00.1.0 core:select-right (input.hidden-input)
```

### Config

```json
{
  "core": {
    "projectHome": "~/Code/",
    "disabledPackages": [
      "language-javascript-jsx",
      "autohide-tree-view",
      "tool-bar",
      "tool-bar-main"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.19
atom-html-preview, v0.1.13
editorconfig, v1.2.2
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-babel, v2.5.3
language-docker, v1.1.3
language-dots, v0.0.4
language-graphql, v0.2.0
language-haskell, v1.5.1
language-rust, v0.4.5
linter, v1.11.3
linter-csslint, v1.1.0
linter-eslint, v5.2.4
linter-jsonlint, v1.1.0
markdown-scroll-sync, v2.0.3
markdown-writer, v2.0.1
pigments, v0.19.1
pretty-json, v0.4.1
react, v0.12.10
set-syntax, v0.3.0
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I'm sorry I haven't gotten to this.  I'm going to need help to reproduce it.  Is it still happening?
