### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by ttf248** [mark-hahn/markdown-scroll-sync#365]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/core/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:262:18)
    at Pane.activate (/usr/share/atom/resources/app/src/pane.js:1002:46)
    at Pane.focus (/usr/share/atom/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -1:20.7.0 core:backspace (input.hidden-input)
     -1:19.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.25.1 
markdown-image-paste 2.5.2 
markdown-preview-plus 2.5.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.0 
markdown-themeable-pdf 1.2.0 
pdf-view 0.65.0 
```

**Comment by huanlin** [comment]
here is a workaround:
https://github.com/vincentcn/markdown-scroll-sync/issues/334
