### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by NjuHaoZhang** [mark-hahn/markdown-scroll-sync#373]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\HaoZhang\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.24.1/resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.24.1/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.24.1/resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.24.1/resources/app/src/pane-container.js:262:18)
    at Pane.activate (~/AppData/Local/atom/app-1.24.1/resources/app/src/pane.js:1002:46)
    at Pane.focus (~/AppData/Local/atom/app-1.24.1/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
 27x -6:49.7.0 editor:newline (input.hidden-input)
     -6:40.9.0 core:save (input.hidden-input)
     -6:36.7.0 editor:newline (input.hidden-input)
     -6:21.2.0 core:save (input.hidden-input)
     -6:14.3.0 editor:newline (input.hidden-input)
  4x -6:10.8.0 core:backspace (input.hidden-input)
     -6:08.5.0 editor:newline (input.hidden-input)
     -6:06.7.0 core:move-up (input.hidden-input)
     -6:06.4.0 editor:newline (input.hidden-input)
     -5:58.6.0 core:move-right (input.hidden-input)
     -5:57.6.0 editor:newline (input.hidden-input)
 17x -5:56.7.0 core:backspace (input.hidden-input)
     -5:54 editor:newline (input.hidden-input)
     -5:53.2.0 core:save (input.hidden-input)
  8x -5:35.7.0 core:backspace (input.hidden-input)
     -5:03.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.25.1 
markdown-image-paste 2.5.2 
markdown-preview-plus 2.5.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.0 
markdown-themeable-pdf 1.2.0 
```

**Comment by NjuHaoZhang** [comment]
My OS is Windows10 professional, thanks

**Comment by hoovler** [comment]
Same issue here.  Figured I'd check the bugs list before creating the ticket.

I too have a Windows 10 OS -- not yet tried this on my Ubuntu partition.  In addition to this package, I have only the following non-based packages installed:

* **language-markdown** _0.25.1_
* **markdown-pdf** _2.1.0_
* **markdown-preview-plus** _2.5.5_
* **markdown-toc** _0.4.2_

**Atom version**: _1.24.1 x64_
