### ISSUE TITLE
Failed to activate the markdown-scroll-sync package

### ISSUE THREAD

**Issue by jerryqiu** [mark-hahn/markdown-scroll-sync#40]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v2.0.3

### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At ENOENT: no such file or directory, lstat '/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou'

Error: ENOENT: no such file or directory, lstat '/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/qiubin/Library/Application Support/com.github.atom.ShipIt/update.jdiT4ou/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "insert-timestamp"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
> update.jdiT4ou

This file was in the middle of being copied by rsync, which is what caused the problem.  I'll see if I can reproduce it.

**Comment by JustinDevelops** [comment]
I am getting this as of today. 
_Also this is my first time really reporting anything so if I am missing something or did something wrong/uncommon any feedback is welcome. :)_ 

**Atom Version:** 1.4.1
**System: Mac OS X** 10.11.3
**Thrown From:** markdown-scroll-sync package, v2.0.3

## Stack
### Failed to activate the markdown-scroll-sync package
```
Module version mismatch. Expected 49, got 47.
Hide Stack Trace
Error: Module version mismatch. Expected 49, got 47.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/oniguruma/lib/oniguruma.js:69:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/grammar.js:10:16)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/grammar.js:365:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/grammar-registry.js:12:13)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/grammar-registry.js:261:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/first-mate.js:4:22)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/first-mate/lib/first-mate.js:8:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/highlights/lib/highlights.js:14:21)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/node_modules/highlights/lib/highlights.js:420:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/lib/renderer.coffee:5:14)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/lib/renderer.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:8:12)
    at Object.<anonymous> (/Users/test/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at MarkdownScrlSync.activate (/Users/test/.atom/packages/markdown-scroll-sync/lib/main.coffee:23:28)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom.app/Contents/Resources/app.asa
```
### The error was thrown from the markdown-scroll-sync package. This issue has already been reported.

**Comment by JustinDevelops** [comment]
and.. Ten minutes after posting the above I fixed it. :) I figured I would report the fix just in-case someone else comes here for a similar issue. 

I noticed I had two bugs in Atom so I clicked the bug icon and found two bugs. I also noticed  a button that suggested I rebuild to fix. I clicked this and the result was successful and upon restarting Atom no more errors. I wish I had thought to capture a screenshot prior to clicking re-build so the success will have to do. 

![screen shot 2016-11-10 at 5 12 07 pm](https://cloud.githubusercontent.com/assets/15177354/20200987/9821b970-a769-11e6-8d06-64ecb9051fdf.png)
