### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by mjsduncan** [mark-hahn/markdown-scroll-sync#420]
## **1. opening a .md document causes this error:**

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu Bionic
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/mozi/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:441:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/src/pane-container.js:263:18)
    at Pane.activate (/usr/share/atom/resources/app/src/pane.js:1010:46)
    at Pane.focus (/usr/share/atom/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -1:07.4.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
autocomplete-python 1.10.5 
autocomplete-R 0.6.0 
expose 0.15.0 
file-icons 2.1.18 
flex-tool-bar 2.0.0 
indent-guide-improved 1.4.13 
language-cmake 1.1.0 
language-markdown 0.25.1 
language-r 0.4.2 
language-scheme 1.4.0 
markdown-preview-plus 2.5.6 
markdown-scroll-sync 2.1.2 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
quick-comment 0.1.3 
sort-lines 0.18.0 
tablr 1.8.3 
tool-bar 1.1.7 
```
**## 2. then clicking the 'Markdown Preview Plus' button link on the toolbar produces this error:**

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu Bionic
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /home/mozi/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/src/workspace.js:441:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/share/atom/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:436:48)
    at Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
autocomplete-python 1.10.5 
autocomplete-R 0.6.0 
expose 0.15.0 
file-icons 2.1.18 
flex-tool-bar 2.0.0 
indent-guide-improved 1.4.13 
language-cmake 1.1.0 
language-markdown 0.25.1 
language-r 0.4.2 
language-scheme 1.4.0 
markdown-preview-plus 2.5.6 
markdown-scroll-sync 2.1.2 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
quick-comment 0.1.3 
sort-lines 0.18.0 
tablr 1.8.3 
tool-bar 1.1.7 
```

**Comment by mjsduncan** [comment]
addendum:  formatted markdown page appears correctly in second pane but scrolling between original and rendered versions is not linked.
