### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by lemonver** [mark-hahn/markdown-scroll-sync#451]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /Users/jiangdingcheng/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:441:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
language-markdown 0.25.1 
markdown-assistant 0.2.0 
markdown-image-paste 2.5.2 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.8 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.0 
markdown-writer 2.7.3 
npm 2.0.0 
npm-install 4.0.4 
```

**Comment by traceflight** [comment]
When I disable markdown-preview-plus and enable markdown-preview, markdown-scroll-sync can works well. Hope this is useful to you.
