### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by SpringJiang** [mark-hahn/markdown-scroll-sync#457]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\Dev\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.26.0/resources/app/src/workspace.js:441:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.26.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.26.0/resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.26.0/resources/app/src/pane.js:444:48)
    at Pane.activateItem (~/AppData/Local/atom/app-1.26.0/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -2:35.4.0 markdown-preview-plus:toggle (markdown-preview-plus-view.native-key-bindings)
     -2:27.2.0 markdown-preview-plus:preview-file (span.name.icon.markdown-icon.medium-blue)
     -1:02.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
file-icons 2.1.18 
language-markdown 0.25.1 
markdown-document 0.2.1 
markdown-image-paste 2.5.2 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 2.5.8 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.0 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.7.3 
pdf-view 0.69.0 
```

**Comment by SpringJiang** [comment]
Disable markdown-preview-plus and Enable markdown-preview can fixed this problem.
