### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by aijunhao** [mark-hahn/markdown-scroll-sync#603]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\AiJunhao\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.28.1/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.28.1/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.28.1/resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.28.1/resources/app/src/pane.js:444:48)
    at Pane.activateItem (~/AppData/Local/atom/app-1.28.1/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:730:25)
```

### Commands

```
undefined -4:33.4.0 markdown:toggle-task (input.hidden-input)
 46x -3:58.1.0 editor:newline (input.hidden-input)
     -3:51.6.0 core:copy (input.hidden-input)
     -3:50.6.0 markdown-img-paste:paste (input.hidden-input)
     -3:49.5.0 editor:newline (input.hidden-input)
     -3:49.1.0 markdown-img-paste:paste (input.hidden-input)
     -3:48.9.0 editor:newline (input.hidden-input)
     -3:48.5.0 markdown-img-paste:paste (input.hidden-input)
     -3:48.3.0 editor:newline (input.hidden-input)
     -3:47.8.0 markdown-img-paste:paste (input.hidden-input)
     -3:47.7.0 editor:newline (input.hidden-input)
  3x -3:38 markdown:toggle-task (input.hidden-input)
  4x -3:06.0 markdown-preview-plus:toggle (input.hidden-input)
     -2:24.5.0 core:save (input.hidden-input)
     -2:14.4.0 markdown-preview-plus:toggle (input.hidden-input)
     -0:29.8.0 markdown-themeable-pdf:export (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.26.0 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.3.2 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 1.2.1 
pdf-view 0.70.0 
qiniu-uploader 0.0.5 
```

**Comment by aijunhao** [comment]
test
