### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by tt82238971** [mark-hahn/markdown-scroll-sync#611]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.5
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

TypeError: Right-hand side of 'instanceof' is not callable

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/src/pane-container.js:263:18)
    at Pane.activate (/private/var/folders/70/94_k1_ks75g9r4kqjyb3sw000000gn/T/AppTranslocation/AACE424E-3F4D-4193-8653-6EC8D16B9F59/d/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at addPreviewForEditor (/packages/markdown-preview-plus/lib/main.js:96:24)
    at <anonymous>
```

### Commands

```
  3x -1:01.4.0 core:backspace (input.hidden-input)
     -0:27.9.0 application:reopen-project (input.hidden-input)
     -0:15.3.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-debug-ui 1.0.4 
atom-ide-ui 0.12.0 
busy-signal 1.4.3 
ide-php 0.7.14 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-writer 2.7.3 
php-debug 0.3.5 
simplified-chinese-menu 5.3.5 
```

**Comment by luoei** [comment]
Has been resolved, please check: https://github.com/vincentcn/markdown-scroll-sync/issues/560
