### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by a308843141** [mark-hahn/markdown-scroll-sync#615]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.5
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

TypeError: Right-hand side of 'instanceof' is not callable

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/src/pane-container.js:263:18)
    at Pane.activate (/Users/davewilliam/Desktop/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at addPreviewForEditor (/packages/markdown-preview-plus/lib/main.js:96:24)
    at <anonymous>
```

### Commands

```
     -0:24 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.26.0 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.4 
qiniu-uploader 0.0.5 
simplified-chinese-menu 5.3.5 
```

**Comment by a308843141** [comment]
error

**Comment by luoei** [comment]
Has been resolved, please check: https://github.com/vincentcn/markdown-scroll-sync/issues/560
