### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by 140041** [mark-hahn/markdown-scroll-sync#616]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Windows 10
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\QiuKe\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane-container.js:263:18)
    at Pane.activate (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane.js:1018:46)
    at Pane.focus (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at HTMLElement.attachedCallback (/app.asar/src/pane-element.js:16:12)
    at HTMLElement.rootChanged (/app.asar/src/pane-container-element.js:26:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.setRoot (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane-container.js:139:24)
    at PaneContainer.deserialize (~/AppData/Local/atom/app-1.28.2/resources/app/src/pane-container.js:59:16)
    at WorkspaceCenter.deserialize (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace-center.js:31:30)
    at Workspace.deserialize (~/AppData/Local/atom/app-1.28.2/resources/app/src/workspace.js:383:40)
    at AtomEnvironment.deserialize (~/AppData/Local/atom/app-1.28.2/resources/app/src/atom-environment.js:1259:47)
    at <anonymous>
```

### Commands

```
     -0:15.3.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-clock 0.1.16 
city-lights-syntax 1.1.8 
file-icons 2.1.22 
git-plus 8.0.0 
highlight-selected 0.14.0 
isotope-light-ui 2.3.0 
markdown-pdf 2.2.0 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.4 
pdf-view 0.70.0 
processing 0.13.0 
processing-language 0.2.0 
sunset 1.3.0 
typewriter-sounds 3.0.1 
```

**Comment by luoei** [comment]
Has been resolved, please check: https://github.com/vincentcn/markdown-scroll-sync/issues/560
