### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by bingo8670** [mark-hahn/markdown-scroll-sync#619]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /Users/zhibinzhao/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:444:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:730:25)
```

### Commands

```
  2x -1:20.5.0 core:confirm (input.hidden-input)
     -0:47.5.0 core:cancel (div.package-detail.panels-item)
     -0:26.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:26.7.0 snippets:expand (input.hidden-input)
     -0:26.6.0 editor:indent (input.hidden-input)
     -0:26.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:26.2.0 snippets:expand (input.hidden-input)
     -0:26.2.0 editor:indent (input.hidden-input)
     -0:25.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:25.9.0 snippets:expand (input.hidden-input)
     -0:25.9.0 editor:indent (input.hidden-input)
     -0:25.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:25.3.0 snippets:expand (input.hidden-input)
     -0:25.3.0 editor:indent (input.hidden-input)
  3x -0:23.5.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-html-preview 0.2.5 
busy-signal 1.4.3 
color-picker 2.3.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.22 
git-plus 8.0.0 
go-plus 5.8.4 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-rubocop 2.2.3 
linter-ui-default 1.7.1 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
minimap 4.29.8 
monokai 0.24.0 
script 3.18.1 
simplified-chinese-menu 5.3.5 
```

**Comment by luoei** [comment]
Has been resolved, please check: https://github.com/vincentcn/markdown-scroll-sync/issues/560

**Comment by bingo8670** [comment]
get it， thank u
