### ISSUE TITLE
Failed to activate the markdown-scroll-sync package

### ISSUE THREAD

**Issue by codrinbucur** [mark-hahn/markdown-scroll-sync#620]
[Enter steps to reproduce:]

1. Simply start Atom

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Failed to activate the markdown-scroll-sync package

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Workspace.observeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:710:11)
    at MarkdownScrlSync.activate (/packages/markdown-scroll-sync/lib/main.coffee:25:30)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.12.1 
atom-xmlvalidate 0.5.0 
autocomplete-asciidoc 0.1.2 
build 0.70.0 
busy-signal 1.4.3 
click-link 1.0.11 
git-plus 8.0.0 
git-time-machine 2.1.0 
intentions 1.1.5 
language-ansible 0.2.2 
language-asciidoc 1.11.0 
language-docker 1.1.8 
language-groovy 0.7.0 
language-markdown 0.26.0 
language-mediawiki 2.2.0 
linter 2.2.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
markdown-preview-plus 3.3.3 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-toolbar 0.1.2 
markdown-writer 2.7.4 
split-diff 1.5.2 
webgrabplus-atom 0.1.3 
xml-formatter 0.11.0 
```

**Comment by luoei** [comment]
Has been resolved, please check: https://github.com/vincentcn/markdown-scroll-sync/issues/560
