### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by zhanpple** [mark-hahn/markdown-scroll-sync#663]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\Administrator\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:263:18)
    at Pane.activate (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:1018:46)
    at PaneContainer.activateNextPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:197:30)
    at Pane.destroy (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:1035:49)
    at Pane.removeItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:708:90)
    at Pane.moveItemToPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:738:16)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:783:26)
    at TabBarView.module.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:660:29)
```

### Commands

```
     -2:27 markdown-preview-plus:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:47.1.0 markdown-preview-plus:toggle-render-latex (webview.markdown-preview-plus.native-key-bindings)
 14x -0:35.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-ternjs 0.18.3 
color-picker 2.3.0 
emmet 2.4.3 
jquery-snippets 11.0.0 
language-markdown 0.26.0 
markdown-img-paste 0.3.11 
markdown-pdf 2.2.0 
markdown-preview-plus 3.3.4 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-writer 2.9.0 
```

**Comment by zhanpple** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2


### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At C:\Users\Administrator\.atom\packages\markdown-scroll-sync\lib\main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:263:18)
    at Pane.activate (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:1018:46)
    at PaneContainer.activateNextPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:197:30)
    at Pane.destroy (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:1035:49)
    at Pane.removeItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:708:90)
    at Pane.moveItemToPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:738:16)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:783:26)
    at TabBarView.module.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:660:29)
```

### Commands

```
     -2:35.6.0 markdown-preview-plus:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:55.8.0 markdown-preview-plus:toggle-render-latex (webview.markdown-preview-plus.native-key-bindings)
 14x -0:44.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-ternjs 0.18.3 
color-picker 2.3.0 
emmet 2.4.3 
jquery-snippets 11.0.0 
language-markdown 0.26.0 
markdown-img-paste 0.3.11 
markdown-pdf 2.2.0 
markdown-preview-plus 3.3.4 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-writer 2.9.0 
```
