### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by nephilimbin** [mark-hahn/markdown-scroll-sync#690]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

TypeError: Right-hand side of 'instanceof' is not callable

```
At Right-hand side of 'instanceof' is not callable

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane-container.js:263:18)
    at Pane.activate (~/AppData/Local/atom/app-1.29.0/resources/app/src/pane.js:1018:46)
    at addPreviewForEditor (/packages/markdown-preview-plus/lib/main.js:96:24)
    at <anonymous>
```

### Commands

```
     -3:27.1.0 markdown-preview-plus:toggle (input.hidden-input)
 38x -2:56 editor:newline (input.hidden-input)
     -1:46.7.0 core:confirm (input.hidden-input)
     -1:12.1.0 application:open-file (div.panels-item)
     -1:06.0 editor:newline (input.hidden-input)
     -1:04.7.0 core:backspace (input.hidden-input)
  2x -1:02.7.0 editor:newline (input.hidden-input)
     -1:00.0 markdown:indent-list-item (input.hidden-input)
     -1:00.0 snippets:next-tab-stop (input.hidden-input)
     -1:00.0 snippets:expand (input.hidden-input)
     -1:00.0 editor:indent (input.hidden-input)
     -0:51.6.0 core:backspace (input.hidden-input)
     -0:33 core:move-right (input.hidden-input)
  2x -0:24.4.0 markdown:toggle-task (input.hidden-input)
     -0:20.2.0 markdown-preview-plus:toggle (input.hidden-input)
     -0:18 markdown-preview-plus:toggle-render-latex (webview.markdown-preview-plus.native-key-bindings)
```

### Non-Core Packages

```
language-markdown 0.26.0 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.4.0 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 1.2.1 
pdf-view 0.71.0 
```

**Comment by nephilimbin** [comment]
please tell me how to handle it.Thanks
