### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed (README closed before preview)

### ISSUE THREAD

**Issue by amarinelli** [mark-hahn/markdown-scroll-sync#7]
1. README.md file is open along with [markdown-preview](https://github.com/atom/markdown-preview) tab
2. If the README.md file is closed *BEFORE* the preview, this error is thrown

**Atom Version**: 0.182.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package, v0.3.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At C:\Users\amarinelli\AppData\Local\atom\app-0.182.0\resources\app\src\display-buffer.js:1005

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (C:\Users\amarinelli\AppData\Local\atom\app-0.182.0\resources\app\src\display-buffer.js:1005:15)
  at TextEditor.module.exports.TextEditor.screenPositionForBufferPosition (C:\Users\amarinelli\AppData\Local\atom\app-0.182.0\resources\app\src\text-editor.js:1228:33)
  at C:\Users\amarinelli\.atom\packages\markdown-scroll-sync\lib\main.coffee:53:23

```

### Commands

```
     -6:31.2 core:confirm (atom-text-editor.editor.mini)
  2x -2:52.2 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-scroll-sync, v0.3.0
minimap, v4.3.1
tidy-markdown, v0.1.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
> Thanks very much for finding such a serious bug

Fixed in 0.3.1
