### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by JARVIS-AI** [mark-hahn/markdown-scroll-sync#784]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.4
**Thrown From**: [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) package 2.1.2

### Stack Trace

Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```
At /Users/jarvismercer/.atom/packages/markdown-scroll-sync/lib/main.coffee:38

TypeError: Right-hand side of 'instanceof' is not callable
    at /packages/markdown-scroll-sync/lib/main.coffee:38:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:430:26)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:12:59)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:265:24)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1018:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
  8x -1:29.6.0 tree-view:toggle (div.panels-item)
     -0:34.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.12.2 
atom-beautify 0.33.2 
atom-clock 0.1.16 
atom-css-comb 3.3.1 
atom-dark-fusion-syntax 2.2.1 
atom-html-templates 0.1.3 
atom-ide-ui 0.13.0 
atom-jade 0.3.0 
atom-material-ui 2.1.3 
atom-oss-license 1.1.2 
atom-typescript 12.6.3 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-asciidoc 0.1.2 
autocomplete-html-entities 0.2.0 
autocomplete-python 1.10.12 
autocomplete-swift 1.0.3 
autohide-tree-view 0.25.1 
busy-signal 1.4.3 
click-link 1.0.11 
color-picker 2.3.0 
disable-keybindings 0.6.0 
django-templates 0.5.0 
docblockr 0.13.7 
drag-relative-path 1.1.3 
duotone-blue-dark-syntax 1.4.0 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-sky-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
duotone-snow 2.2.0 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.25 
firewatch-syntax 1.1.1 
git-control 0.9.0 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
hyperlink-hyperclick 2.0.0 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-fortran 0.3.0 
ide-go 0.12.3 
ide-haskell 2.3.1 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-powershell 0.1.0 
ide-purescript 0.24.0 
ide-python 1.0.0 
ide-r 0.1.8 
ide-rust 0.18.3 
ide-scala 0.7.0 
ide-typescript 0.7.9 
ide-vue 0.1.9 
language-asciidoc 1.11.0 
language-awk 0.1.12 
language-babel 2.85.0 
language-elixir 0.22.1 
language-fortran 2.1.7 
language-gitignore 0.3.0 
language-haskell 1.17.8 
language-ini-desktop 1.18.3 
language-lua 0.9.11 
language-markdown 0.27.0 
language-powershell 5.0.0 
language-prolog 0.11.0 
language-qml 1.1.0 
language-qt-qrc 3.0.0 
language-rust 0.4.12 
language-swift 0.5.0 
markdown-preview-plus 3.7.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.9.0 
material 2.2.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
NewFirewatch-syntax 1.2.0 
no-title-bar 1.11.4 
oceanic-next 1.0.0 
operator-mono 0.11.0 
perltidy 4.0.0 
pigments 0.40.2 
pretty-json 2.0.3 
pristine-ui 1.1.11 
react 0.18.0 
sort-lines 0.18.0 
spacegray-dark-neue-ui 1.7.1 
svg-preview 0.14.0 
terminal-tab-service 0.1.4 
todo-show 2.3.2 
tool-bar 1.1.10 
tool-bar-almighty 0.8.2 
tool-bar-atom 1.7.0 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.5.0 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.5.2 
unity-ui 2.1.11 
```

**Comment by JARVIS-AI** [comment]
only when `markdown-preview-plus 3.7.0` is enabled this error throw out.
Tested
Not conflict with Github core package and markdown-preview

But for other markdown packages throw error.
